# single test suite, non-parallel build.

env:
  global:
    - CC_TEST_REPORTER_ID=f7b6c5f939f55bad836bc60bdd37df06ae90dcc8b3bdb58d7b609ea95363f830
language: node_js
node_js:
  - '10.14.1'
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run test
  - npm run coverage
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
